// ui/components/log_tab.slint
import { VerticalBox, TextEdit } from "std-widgets.slint";
import { Theme } from "theme.slint";

export component LogTab inherits Rectangle {
    background: #141414;
    border-radius: 4px;
    border-width: 1px;
    border-color: Theme.card_border;

    in-out property <string> log_text: "";

    VerticalBox {
        padding: 8px;
        TextEdit {
            read-only: true;
            text: root.log_text;
            font-family: "Consolas";
            font-size: 12px;
            wrap: word-wrap;
        }
    }
}
